# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_auto_20170116_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('dateOfBirth', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
