# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_auto_20170116_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notenames',
            name='dateOfBirth',
            field=models.DateField(),
        ),
    ]
